site_name: programki.eu
theme:
  name: material
nav:
  - Home: index.md
  - post01: post01.md
  - post06: post06.md
  - post07: post07.md
  - post08: post08.md
  - post09: post09.md
extra:
  analytics:
    provider: google
    property: G-MZ0JN1EDPS
