site_name: programki.eu
theme:
  name: material
  features:
    - content.code.copy
plugins:
  - blog:
      blog_dir: . 
  - search
  - tags
nav:
  - index.md
extra:
  analytics:
    provider: google
    property: G-MZ0JN1EDPS
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences