site_name: programki.eu
theme:
  name: material
features:
    - navigation.sections
plugins:
  - blog:
      blog_dir: . 
  - search
  - tags
nav:
  - index.md
extra:
  analytics:
    provider: google
    property: G-MZ0JN1EDPS
